### PR TITLE
Update user guide

### PR DESCRIPTION
**Pull request by tdearden**
Copy changes and updated/new GIFS for user-guide and images/user-guide. Updated GIFs as below: 

data-catalogue DELETE:
2.1-How-do-I-find-data.gif
2.2-How-do-I-find-data.gif
4.1-What-do-the-button-colours-mean.png
5.1-How-do-I-layer-the-views.gif
6.3-The-view-toolbar.gif
8.1-How-do-I-make-a-map.gif
8.2-How-do-I-make-a-map.gif
8.3-How-do-I-make-a-map.gif
8.4-How-do-I-make-a-map.gif
10.2-toolbox-features.png
11-sharing-views.gif

data-catalogue ADD:
(* denotes new slide or accordion widget, rather than just replacement)
2.1-How-do-I-find-data-NEW.gif
2.2-How-do-I-find-data-NEW.gif
*2.3-How-do-I-find-data-NEW.gif
*3-custom-categories-NEW.gif
4.1-What-do-the-button-colours-mean-NEW.jpg
*4.4-What-do-the-button-colours-mean-NEW.png
6.3-The-view-toolbar-NEW.gif
8.1-How-do-I-make-a-map-NEW.gif
8.2-How-do-I-make-a-map-NEW.gif
8.3-How-do-I-make-a-map-NEW.gif
9.1-How-do-I-create-features-NEW.gif
10.2-toolbox-features-NEW.png
11-sharing-views-NEW.gif
12-Highlight-intersecting-features-NEW.gif
13-attribute-table-NEW.gif

data-catalogue CHANGE:
9-Reset-Bearing.gif change to 5-Reset-Bearing.gif

6nr DELETE:
3-How-can-I-share-a-project.gif
4.2-add-or-delete-views.gif

6nr ADD:
4.2-add-or-delete-views-NEW.gif

### CODE REVIEW

**Comment by WKocur** [comment]
Hi @tdearden  - I've just had a look through this PR :) Seems you need to rename the 9-Reset-Bearing.gif file to be 5-Reset-Bearing.gif. Also, is there a reason you've kept the old GIFs, rather than delete them? If you don't need them then it keeps the repo cleaner to delete them. Otherwise all looks good to me!

**Comment by tdearden** [comment]
Hi @WKocur , thanks! I couldn't figure out how to rename the .gif so I changed the name back to 9-Reset-Bearing.gif in user-guide. Hopefully this makes sense? And no, we don't need to keep the old GIFs (not sure what repo cleaner is).

**Comment by WKocur** [comment]
@tdearden Yep, that works too. Ah sorry, by repo I mean repository. Just means we don't have unused files lying about. Are you ok to delete the ones that are no longer used? Once that's done, I think this is good to merge :)

**Comment by tdearden** [comment]
@WKocur Ok, I've deleted the extra ones :) All good?

**Comment by WKocur** [comment]
@tdearden Great, thanks! I think sharing-views.gif needs to still be there as it's being used in How Can I Share a View or Project?

**Comment by tdearden** [comment]
@WKocur oops, that would have been bad. There is a new GIF linked there now: 11-sharing-views-NEW.gif

**Comment by WKocur** [comment]
@tdearden Looks good - I'll merge! :)

**Pull request merged**
